import * as React from "react";
import * as Types from "./types";

declare function MolocoLocations(props: {
  as?: React.ElementType;
  locationYellowText?: React.ReactNode;
  locationHeadingText?: React.ReactNode;
  siliconValleyImage?: Types.Asset.Image;
  sanFransiscoImage?: Types.Asset.Image;
  seattleImage?: Types.Asset.Image;
  beijingImage?: Types.Asset.Image;
  londonImage?: Types.Asset.Image;
  seoulImage?: Types.Asset.Image;
  singaporeImage?: Types.Asset.Image;
  tokyoImage?: Types.Asset.Image;
  siliconValleyHoverText?: React.ReactNode;
  sanfranciscoHoverText?: React.ReactNode;
  seattleHoverText?: React.ReactNode;
  beijingHoverText?: React.ReactNode;
  londonHoverText?: React.ReactNode;
  seoulHoverText?: React.ReactNode;
  singaporeHoverText?: React.ReactNode;
  tokyoHoverText?: React.ReactNode;
  _1stLocation?: React.ReactNode;
  _2ndLocationTitle?: React.ReactNode;
  _3rdLocationTitle?: React.ReactNode;
  _4thLocationTitle?: React.ReactNode;
  _5thLocationTitle?: React.ReactNode;
  _6thLocationTitle?: React.ReactNode;
  _7thLocationTitle?: React.ReactNode;
  _8thLocationTitle?: React.ReactNode;
  nyTitle?: React.ReactNode;
  nyImage?: Types.Asset.Image;
  nyHoverText?: React.ReactNode;
  indiaTitle?: React.ReactNode;
  indiaImage?: Types.Asset.Image;
  indiaHoverText?: React.ReactNode;
  laTitle?: React.ReactNode;
  laImage?: Types.Asset.Image;
  laHoverText?: React.ReactNode;
  berlinTitle?: React.ReactNode;
  berlinHoverText?: React.ReactNode;
  berlinImage?: Types.Asset.Image;
}): React.JSX.Element;
